language: minimal
os: linux
arch: amd64
dist: hirsute
branches: 
  except:
    - CI-latest
script:
- sudo apt-get install -y texlive-base texlive-latex-extra texlive-xetex latexmk xzdec 
- sudo apt-get install -y sshpass
- sudo tlmgr init-usertree 
- sudo tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2020/tlnet-final/
- sudo tlmgr install bibtex IEEEtran tools url arydshln booktabs sttools etoolbox titlesec appendix parskip kvoptions ltxcmds kvsetkeys float caption tikzpagenodes pgf ifoddpage imakeidx xkeyval nowidow hyperref infwarerr textpos enumitem tcolorbox environ listings wrapfig needspace ean ocr-b changepage tabulary multirow geometry zapfding helvetic iftex || true
- latex --version
- sudo updmap-sys
- git -C .. clone https://github.com/MEGA65/mega65-libc.git
- git -C .. clone --branch=development https://github.com/MEGA65/mega65-core.git
- sudo make mega65-book.pdf || true
- sudo make mega65-book.pdf
- sudo make mega65-basic65-reference.pdf || true
- sudo make mega65-basic65-reference.pdf
- sudo make mega65-chipset-reference.pdf || true
- sudo make mega65-chipset-reference.pdf
- sudo make mega65-developer-guide.pdf || true
- sudo make mega65-developer-guide.pdf
- sudo make mega65-userguide.pdf || true
- sudo make mega65-userguide.pdf
after_script:
- ./genhtml.sh
- ssh-keygen -R ${SFTP_SERVER}
- sshpass -p ${SFTP_PASSWORD} scp -o StrictHostKeyChecking=no -P ${SFTP_PORT} *.pdf ${SFTP_USER}@${SFTP_SERVER}:manuals-upload/
- sshpass -p ${SFTP_PASSWORD} scp -o StrictHostKeyChecking=no -P ${SFTP_PORT} *.log ${SFTP_USER}@${SFTP_SERVER}:manuals-upload/
- sshpass -p ${SFTP_PASSWORD} scp -o StrictHostKeyChecking=no -P ${SFTP_PORT} index.html ${SFTP_USER}@${SFTP_SERVER}:manuals-upload/
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: 
  - $TRAVIS_BUILD_DIR/*.pdf
  - $TRAVIS_BUILD_DIR/*.log
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: 176_automate_doc_build
